# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Matthew/Documents/VivadoStuff/lab6_2_restart/lab6_2_restart.srcs/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0.xci
# IP: The module: 'mb_usb_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthew/Documents/VivadoStuff/lab6_2_restart/lab6_2_restart.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Matthew/Documents/VivadoStuff/lab6_2_restart/lab6_2_restart.srcs/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0.xci
# IP: The module: 'mb_usb_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matthew/Documents/VivadoStuff/lab6_2_restart/lab6_2_restart.gen/sources_1/bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
