# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/srira/OneDrive/Desktop/ECE385/ECE385-sanjits2_mzwu3/lab6_2_restart/lab6_2_restart.srcs/sources_1/ip/hatman_rom/hatman_rom.xci
# IP: The module: 'hatman_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srira/OneDrive/Desktop/ECE385/ECE385-sanjits2_mzwu3/lab6_2_restart/lab6_2_restart.gen/sources_1/ip/hatman_rom/hatman_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hatman_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/srira/OneDrive/Desktop/ECE385/ECE385-sanjits2_mzwu3/lab6_2_restart/lab6_2_restart.srcs/sources_1/ip/hatman_rom/hatman_rom.xci
# IP: The module: 'hatman_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/srira/OneDrive/Desktop/ECE385/ECE385-sanjits2_mzwu3/lab6_2_restart/lab6_2_restart.gen/sources_1/ip/hatman_rom/hatman_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hatman_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
